- hosts: 127.0.0.1
  connection: local
  become: true

  pre_tasks:
    - name: Load Vault
      ansible.builtin.include_vars: "group_vars/vault"
    - name: Load configuration
      ansible.builtin.include_vars: "group_vars/vars.yml"

  roles:
    - role: base
    - role: user
    - role: time
    - role: pacman
    - role: sudo
    - role: iwd
    - role: sway
    - role: git
    - role: kitty
    - role: firefox
    - role: rofi
    - role: yay
    - role: i3status-rust-git
    - role: vscode
    - role: debug
      vars:
        variables:
          - ansible_facts
          - "!all"
