- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Load Vault
      ansible.builtin.include_vars: "group_vars/vault"
    - name: Load common configuration libs
      ansible.builtin.include_vars: "group_vars/common-lib.yml"
    - name: Load machine specific configuration
      ansible.builtin.include_vars: "group_vars/machine/{{ ansible_hostname | lower }}.yml"

  roles:
    - role: base
    - role: user
    - role: time
    - role: pacman
    - role: sudo
    - role: iwd
      when: "conf.wifi is defined"
    - role: dhclient
      when: "conf.dhclient is defined"
    - role: sway
    - role: git
    - role: kitty
    - role: firefox
      when: "conf.browser == 'firefox'"
    - role: qutebrowser
      when: "conf.browser == 'qutebrowser'"
    - role: rofi
    - role: yay
    - role: i3status-rust-git
    - role: vscode
    - role: vagrant
      when: "conf.vagrant is defined"
      vars:
        vagrant_plugins: # TODO: Make configurable
          - vagrant-libvirt
    - role: php
      when: "conf.dev.php is defined"
    # - role: debug
    #   vars:
    #     variables:
    #       - ansible_facts
    #       - "!all"
