---
- name: Ensure dependencies are installed (Archlinux).
  when: ansible_facts.os_family == "Archlinux"
  become: true
  community.general.pacman:
    name:
      # Includes command-not-found.bash
      - pkgfile
      # File finder
      - broot
    state: present

- name: Ensure group sudo exists.
  become: true
  ansible.builtin.group:
    name: "sudo"
    state: present

- name: Ensure user {{ conf.user.username }} exists.
  become: true
  ansible.builtin.user:
    name: "{{ conf.user.username }}"
    password: "{{ conf.user.password | password_hash('sha512') }}"
    update_password: "on_create"
    groups: 
      - "sudo" # TODO: Move to sudo role
    append: yes
    state: present

- name: Copy {{ role_name }} configuration.
  become_user: "{{ conf.user.username }}"
  ansible.builtin.copy:
    src: "{{ role_name }}/"
    dest: "~/"
    mode: preserve

- name: Copy bash configuration.
  become_user: "{{ conf.user.username }}"
  ansible.builtin.copy:
    src: "bash"
    dest: "~/.config/"
    mode: preserve
