---
- name: Ensure dependencies are installed (Archlinux).
  when: ansible_facts.os_family == "Archlinux"
  become_user: "{{ username }}"
  kewlfft.aur.aur:
    use: yay
    state: present
    name:
      - visual-studio-code-bin

# - name: Copy {{ role_name }} configuration.
#   become_user: "{{ username }}"
#   ansible.builtin.copy:
#     src: "Code"
#     dest: "~/.config/"
#     mode: preserve