---
- name: Ensure dependencies are installed (Archlinux).
  when: ansible_facts.os_family == "Archlinux"
  become: true
  community.general.pacman:
    name: kitty
    state: present

- name: Copy {{ role_name }} configuration.
  become_user: "{{ conf.user.username }}"
  ansible.builtin.copy:
    src: "kitty"
    dest: "~/.config/"
    mode: preserve