---
# TODO: Configure wofi in sway config
- name: Ensure dependencies are installed (Archlinux).
  when: ansible_facts.os_family == "Archlinux"
  become: true
  community.general.pacman:
    name: wofi
    state: present

# - name: Copy {{ role_name }} configuration.
#   become_user: "{{ username }}"
#   ansible.builtin.copy:
#     src: "wofi"
#     dest: "~/.config/"