---
- name: Ensure dependencies are installed (Archlinux).
  when: ansible_facts.os_family == "Archlinux"
  become_user: "{{ username }}"
  kewlfft.aur.aur:
    name: i3status-rust-git
    use: yay
    state: present

- name: Copy {{ role_name }} configuration.
  become_user: "{{ username }}"
  ansible.builtin.copy:
    src: "{{ansible_hostname}}/i3status-rust"
    dest: "~/.config/"