---
- name: Ensure dependencies are installed (Archlinux).
  when: ansible_facts.os_family == "Archlinux"
  become: true
  community.general.pacman:
    name:
      - neovim
      - python-neovim
    state: present

- name: Copy {{ role_name }} service configuration.
  become_user: "{{ conf.user.username }}"
  ansible.builtin.copy:
    src: "./"
    dest: "~/.config/nvim/"
    mode: preserve

- name: Copy {{ role_name }} service configuration.
  become_user: "{{ conf.user.username }}"
  loop:
    - "./lunarvim/init.lua"
    - "./lunarvim/lua"
    - "./lunarvim/snapshots"
    - "./lunarvim/ftdetect"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/.config/nvim/"
    mode: preserve

